name: credenciales_web
description: "Credenciales Web App"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  http: ^1.5.0
  postgres: ^3.5.7
  url_launcher: ^6.3.2
  file_picker: ^8.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    

